"""
Jira Task Manager

Creates and updates Jira issues for the eShop Azure migration project
using the Atlassian MCP client.
"""

import logging
from dataclasses import dataclass

from .analyzer import MigrationTask, ModernizationPlan
from .mcp_client import AtlassianMCPClient

logger = logging.getLogger(__name__)


@dataclass
class JiraTaskResult:
    """Result of creating or updating a Jira issue."""

    action: str  # "created" | "updated" | "skipped"
    issue_key: str
    summary: str
    url: str = ""
    error: str = ""

    @property
    def succeeded(self) -> bool:
        return not self.error


class JiraTaskManager:
    """
    Creates and updates Jira issues for Azure migration tasks.

    For each :class:`~analyzer.MigrationTask` in a plan:
    - Searches for an existing issue with the same title.
    - Updates it if found, or creates a new one if not.
    - Adds an AI-generated description comment on updates.
    """

    def __init__(
        self,
        mcp_client: AtlassianMCPClient,
        project_key: str = "ESHOP",
        epic_key: str | None = None,
    ):
        self.client = mcp_client
        self.project_key = project_key
        self.epic_key = epic_key

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def sync_plan(self, plan: ModernizationPlan) -> list[JiraTaskResult]:
        """
        Synchronise a full :class:`ModernizationPlan` with Jira.

        Returns one :class:`JiraTaskResult` per task.
        """
        results: list[JiraTaskResult] = []
        for task in plan.tasks_by_priority():
            result = self._sync_task(task)
            results.append(result)
            if result.succeeded:
                logger.info(
                    "[%s] %s → %s (%s)",
                    result.action.upper(),
                    result.issue_key,
                    result.summary,
                    result.url or "no url",
                )
            else:
                logger.error(
                    "Failed to sync task %r: %s", task.title, result.error
                )
        return results

    def create_epic_summary_comment(
        self, epic_key: str, plan: ModernizationPlan, task_results: list[JiraTaskResult]
    ) -> bool:
        """Post an AI-analysis summary comment on the migration epic."""
        created = [r for r in task_results if r.action == "created"]
        updated = [r for r in task_results if r.action == "updated"]
        skipped = [r for r in task_results if r.action == "skipped"]
        failed = [r for r in task_results if r.error]

        comment_lines = [
            "🤖 *AI-Assisted Modernization Analysis Complete*",
            "",
            f"*Summary:* {plan.summary}",
            "",
            f"*Risk Assessment:* {plan.risk_assessment}",
            "",
            "*Recommended Migration Phases:*",
        ]
        for phase in plan.recommended_phases:
            comment_lines.append(f"# {phase}")
        comment_lines += [
            "",
            "*Sync Results:*",
            f"  * ✅ Created: {len(created)} issue(s)",
            f"  * 🔄 Updated: {len(updated)} issue(s)",
            f"  * ⏭  Skipped: {len(skipped)} issue(s)",
            f"  * ❌ Failed:  {len(failed)} issue(s)",
            "",
            "_Generated by Rovo MCP Demo Agent_",
        ]

        response = self.client.add_jira_comment(
            issue_key=epic_key,
            comment="\n".join(comment_lines),
        )
        if response.success:
            logger.info("Summary comment added to epic %s.", epic_key)
            return True
        logger.error("Failed to add comment to %s: %s", epic_key, response.error)
        return False

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _find_existing_issue(self, summary: str) -> dict | None:
        """Search for a Jira issue whose summary matches *summary*."""
        jql = (
            f'project = "{self.project_key}" '
            f'AND summary ~ "{summary[:60]}" '
            f'AND issuetype in (Story, Task, Sub-task) '
            f'ORDER BY created DESC'
        )
        response = self.client.search_jira_issues(jql, max_results=5)
        if not response.success:
            return None
        issues = response.data.get("issues", [])
        # Exact (case-insensitive) match preferred
        for issue in issues:
            if issue.get("summary", "").lower() == summary.lower():
                return issue
        return None

    def _sync_task(self, task: MigrationTask) -> JiraTaskResult:
        """Create or update the Jira issue for *task*."""
        existing = self._find_existing_issue(task.title)

        if existing:
            return self._update_task(task, existing)
        return self._create_task(task)

    def _create_task(self, task: MigrationTask) -> JiraTaskResult:
        """Create a new Jira issue for *task*."""
        priority_map = {
            "Critical": "Highest",
            "High": "High",
            "Medium": "Medium",
            "Low": "Low",
        }
        response = self.client.create_jira_issue(
            project_key=self.project_key,
            summary=task.title,
            description=task.to_jira_description(),
            issue_type="Story",
            priority=priority_map.get(task.priority.value, "Medium"),
            labels=task.labels,
            epic_link=self.epic_key,
        )
        if response.success:
            data = response.data
            return JiraTaskResult(
                action="created",
                issue_key=data.get("key", ""),
                summary=task.title,
                url=data.get("url", ""),
            )
        return JiraTaskResult(
            action="created",
            issue_key="",
            summary=task.title,
            error=response.error or "unknown error",
        )

    def _update_task(self, task: MigrationTask, existing: dict) -> JiraTaskResult:
        """Update an existing Jira issue with refreshed analysis."""
        issue_key = existing.get("key", existing.get("id", ""))
        response = self.client.update_jira_issue(
            issue_key=issue_key,
            description=task.to_jira_description(),
            labels=task.labels,
        )
        if not response.success:
            return JiraTaskResult(
                action="updated",
                issue_key=issue_key,
                summary=task.title,
                error=response.error or "unknown error",
            )

        # Add a comment noting the AI update
        comment = (
            f"🤖 *AI Analysis Update* – {task.category.value} | "
            f"Priority: {task.priority.value} | "
            f"Azure Service: {task.azure_service} | "
            f"Estimated Effort: {task.estimated_effort}"
        )
        self.client.add_jira_comment(issue_key=issue_key, comment=comment)

        return JiraTaskResult(
            action="updated",
            issue_key=issue_key,
            summary=task.title,
            url=response.data.get("url", ""),
        )
